import pandas as pd
import numpy as np
import warnings
from Bio import codonalign
from Bio.Seq import Seq
import gffutils
import allel
from .sequence_utils import (
    _sort_vcf, count_sites, mean_ss_sites, get_nucleotide_sequences,
    get_aa_sequences, identify_ss_ns_sites, convert_to_binaryarray,
)
from .stat_utils import (
    triang2df_fst, calc_pi, calc_theta, calc_taj,
    calc_fst_btwn, calc_fst_pairwise, calc_fst_wc,
)


class Gene:
    def __init__(self, name, chromosome=None, start=None, end=None, statistics=None,
                 vcf=None, annotation=None, fasta=None, metadata=None):
        self.name = name
        self.chromosome = chromosome
        self.start = start
        self.end = end
        self.length = end - start + 1 if start is not None and end is not None else None
        self.gc_content = None
        self.samples = None
        self.locs = None
        self.transcripts = {}
        self.statistics = statistics if statistics is not None else {
            'pi': True, 'theta': True, 'tajD': True, 'Fst': True, 'pairwiseFst': False
        }
        self.vcf = vcf
        self.annotation = annotation
        self.fasta = fasta
        self.metadata = pd.read_csv(metadata, sep='\t') if metadata is not None else None

    def __repr__(self):
        loc = f'{self.chromosome}:{self.start}-{self.end}' if self.chromosome else 'location unknown'
        length = f'{self.length} bp' if self.length else 'length unknown'
        tx_ids = list(self.transcripts.keys())
        tx_str = f'{len(tx_ids)} ({", ".join(tx_ids)})' if tx_ids else 'none loaded'
        stat_flags = {k: v for k, v in self.statistics.items() if isinstance(v, bool)}
        enabled = [k for k, v in stat_flags.items() if v]
        disabled = [k for k, v in stat_flags.items() if not v]
        stat_str = ', '.join(enabled)
        if disabled:
            stat_str += f' [{", ".join(disabled)} disabled]'
        gc = f'{self.gc_content:.3f}' if self.gc_content is not None else 'N/A'
        return (
            f'Gene: {self.name}\n'
            f'  Location: {loc}  |  Length: {length}  |  GC: {gc}\n'
            f'  Transcripts: {tx_str}\n'
            f'  Statistics: {stat_str}'
        )

    def __len__(self):
        return len(self.transcripts)

    def __iter__(self):
        return iter(self.transcripts.values())

    def __getitem__(self, key):
        return self.transcripts[key]

    def fetch_gene_coordinates(self, annotation=None, fasta=None):
        """Fetch gene coordinates from a GFF database generated by parse_gff.py."""
        
        if annotation is not None:
            self.annotation = annotation
        if fasta is not None:
            self.fasta = fasta
        db = gffutils.FeatureDB(self.annotation, keep_order=True)
        feature = db[self.name]
        self.chromosome = feature.chrom
        self.start = feature.start
        self.end = feature.end
        self.length = self.end - self.start + 1
        seq = feature.sequence(self.fasta, use_strand=False)
        self.gc_content = (seq.count('G') + seq.count('C')) / len(seq) if len(seq) > 0 else 0
        return feature.chrom, feature.start, feature.end

    def fetch_gene_transcripts(self, annotation=None, transcriptID='mRNA'):
        """Fetch transcripts for a given gene from a GFF database."""
        if annotation is not None:
            self.annotation = annotation
        db = gffutils.FeatureDB(self.annotation, keep_order=True)
        transcripts = list(db.children(self.name, featuretype=transcriptID))
        stat_flags = {k: v for k, v in self.statistics.items() if isinstance(v, bool)}
        self.transcripts = {
            t.id: Transcript(id=t.id, gene=self.name, annotation=self.annotation,
                             fasta=self.fasta, vcf=self.vcf, chromosome=t.chrom,
                             start=t.start, end=t.end, statistics=dict(stat_flags))
            for t in transcripts
        }
        return transcripts

    def fetch_coding_sequence(self, transcript, annotation=None, fasta=None, cdsID='CDS'):
        """Fetch the coding sequence for a transcript, sorting CDS features by their numeric ID.

        Accepts either a Transcript object (returns its coding_seq directly) or a raw
        gffutils feature (creates a Transcript, stores it in self.transcripts, and returns
        its coding_seq).
        """
        if annotation is not None:
            self.annotation = annotation
        if fasta is not None:
            self.fasta = fasta
        if isinstance(transcript, Transcript):
            self.transcripts[transcript.id] = transcript
            return transcript.coding_seq
        # transcript is a raw gffutils feature — wrap it in a Transcript
        stat_flags = {k: v for k, v in self.statistics.items() if isinstance(v, bool)}
        tx = Transcript(id=transcript.id, gene=self.name, annotation=self.annotation,
                        fasta=self.fasta, vcf=self.vcf, chromosome=transcript.chrom,
                        start=transcript.start, end=transcript.end, statistics=dict(stat_flags))
        self.transcripts[transcript.id] = tx
        return tx.coding_seq

    def fetch_variation(self, vcf=None, annotation=None, fasta=None,
                        protein_fasta=None, filter=None):
        """Load variant data for all transcripts from a VCF file."""
        if vcf is not None:
            self.vcf = vcf
        if annotation is not None:
            self.annotation = annotation
        if fasta is not None:
            self.fasta = fasta
        chrval = self.chromosome.split('_')[-1] if '_' in self.chromosome else self.chromosome
        callset = allel.read_vcf(self.vcf, region=f'{chrval}:{self.start}-{self.end}')
        if self.metadata is not None:
            callset, sampleIDs, sampleLOCs = _sort_vcf(callset, self.metadata)
            self.samples = sampleIDs
            self.locs = sampleLOCs
        if filter is not None:
            filter_callset = allel.read_vcf(filter, region=f'{chrval}:{self.start}-{self.end}')
            keeppos = np.isin(callset['variants/POS'], filter_callset['variants/POS'])
            for key in callset.keys():
                if key.startswith('variants/') or key.startswith('calldata/'):
                    callset[key] = callset[key][keeppos]
        if not self.transcripts:
            print(f"Fetching transcripts for gene {self.name} on chromosome {chrval}")
            self.fetch_gene_transcripts()
        for tx_id, tx in self.transcripts.items():
            if not isinstance(tx, Transcript):
                # raw gffutils feature — wrap it; fetch_coding_sequence stores the Transcript
                self.fetch_coding_sequence(tx)
                tx = self.transcripts[tx_id]
            coding_seq = tx.coding_seq
            cds_seq, cds_seq_array = get_nucleotide_sequences(callset, coding_seq)
            wt_AA_seq, aa_array = get_aa_sequences(cds_seq_array, cds_seq, ID=tx_id, fasta_check=protein_fasta)
            sitesval = mean_ss_sites(cds_seq_array, wt_AA_seq)
            synonymous_array, nonsynonymous_array = identify_ss_ns_sites(cds_seq_array, cds_seq, aa_array, wt_AA_seq)
            tx.samples = self.samples
            tx.locs = self.locs
            tx.variants = Variants(
                callset=callset,
                wt_nt_seq=cds_seq,
                wt_aa_seq=wt_AA_seq,
                cds_seq_array=cds_seq_array,
                aa_seq_array=aa_array,
                synarr=synonymous_array,
                nonarr=nonsynonymous_array,
                mean_nssites=sitesval[1],
                mean_ssites=sitesval[0],
                locs=self.locs,
            )

    def keep_longest_transcript(self):
        """Keep only the longest transcript for the gene, removing all others."""
        if not self.transcripts:
            print(f"No transcripts loaded for gene {self.name}. Cannot keep longest transcript.")
            return
        longest_tx_id = max(self.transcripts, key=lambda tid: self.transcripts[tid].cds_length)
        self.transcripts = {longest_tx_id: self.transcripts[longest_tx_id]}

    def calculate_statistics(self, statistics=None):
        """Calculate statistics for one or all transcripts.

        Results are stored on each Transcript object as tx.statistics (a DataFrame)
        and tx.pairwise_fst.
        """
        if statistics is None:
            stat_flags = {k: v for k, v in self.statistics.items() if isinstance(v, bool)}
        else:
            stat_flags = {k: True for k in statistics}
        tx_ids = list(self.transcripts.keys())
        for tid in tx_ids:
            tx = self.transcripts[tid]
            tx.variants.calculate_statistics(stat_flags)
            tx.statistics = tx.variants.statistics
            tx.pairwise_fst = tx.variants.pairwise_fst

    def save_to_df(self, transcriptID, output_file='stats_output.txt', append=True):
        """Write statistics to a tab-separated file."""
        tx = self.transcripts[transcriptID]
        stats_df = tx.statistics
        pairwise_fst = tx.pairwise_fst
        if pairwise_fst is not None:
            pairwise_fst.to_csv(output_file.replace('.txt', f'_{transcriptID}_pairwiseFst.txt'),
                                sep='\t', index=False)
        if append:
            with open(output_file, 'a') as f:
                f.write(f'{self.name}\t{self.chromosome}\t{transcriptID}\t{self.length}\t{self.gc_content}\t')
                for stat in stats_df.index:
                    for level in stats_df.columns:
                        f.write(f'{stats_df.loc[stat, level]}\t')
                f.write('\n')
        else:
            with open(output_file, 'w') as f:
                f.write('Gene\tChromosome\tTranscript\tLength\tGC_Content\t')
                for stat in stats_df.index:
                    for level in stats_df.columns:
                        f.write(f'{stat}_{level}\t')
                f.write(f'\n{self.name}\t{self.chromosome}\t{transcriptID}\t{self.length}\t{self.gc_content}\t')
                for stat in stats_df.index:
                    for level in stats_df.columns:
                        f.write(f'{stats_df.loc[stat, level]}\t')
                f.write('\n')


class Transcript:
    def __init__(self, id, gene, annotation, fasta, vcf, chromosome=None, start=None, end=None,
                 statistics=None):
        db = gffutils.FeatureDB(annotation, keep_order=True)
        cds = list(db.children(id, featuretype='CDS'))
        # sort CDS features by their numeric ID to maintain correct biological order
        cdsN = [int(c.id.split('CDS')[1]) for c in cds]
        cdsid = [c.id for c in cds]
        cdsstart = [c.start for c in cds]
        cdsend = [c.end for c in cds]
        cdsseq = [c.sequence(fasta, use_strand=False) for c in cds]
        cdsN, cdsid, cdsstart, cdsend, cdsseq = zip(*sorted(zip(cdsN, cdsid, cdsstart, cdsend, cdsseq)))
        cdsstrand = cds[0].strand if cds else None
        self.coding_seq = {
            'id': id,
            'cds_id': cdsid,
            'cds_start': cdsstart,
            'cds_end': cdsend,
            'cds_seq': cdsseq,
            'strand': cdsstrand
        }
        self.id = id
        self.gene = gene
        self._chromosome = chromosome
        self._start = start
        self._end = end
        if cdsstrand == '-':
            nt_seq = [str(Seq(x).reverse_complement()) for x in cdsseq]
            self.NTseq = np.fromiter("".join(nt_seq), dtype='U1')
        else:
            self.NTseq = np.fromiter("".join(cdsseq), dtype='U1')
        self.cds_length = len(self.NTseq)
        self.AAseq = np.fromiter(codonalign.codonseq.CodonSeq("".join(self.NTseq)).translate(), dtype='U1')
        self.samples = None
        self.locs = None
        self.variants = None
        self.pairwise_fst = None
        self.statistics = statistics if statistics is not None else {
            'pi': True, 'theta': True, 'tajD': True, 'Fst': False, 'pairwiseFst': False
        }
        self.vcf = vcf
        self.annotation = annotation
        self.fasta = fasta

    def __repr__(self):
        has_variants = self.variants is not None
        has_stats = isinstance(self.statistics, pd.DataFrame) and not self.statistics.empty
        lines = [
            f'Transcript: {self.id}  (Gene: {self.gene})',
            f'  CDS length: {self.cds_length} bp  |  Protein length: {len(self.AAseq)} aa',
            f'  Variants loaded: {"Yes" if has_variants else "No"}',
        ]
        if has_stats:
            lines.append('  Statistics:')
            lines.append(self.statistics.to_string(float_format='{:.6f}'.format))
        return '\n'.join(lines)

    def load_variation(self, vcf, samples=None, filter=None, protein_fasta=None):
        """Fetch variants for a given transcript from a VCF file."""
        self.vcf = vcf
        chrval = self._chromosome.split('_')[-1] if '_' in self._chromosome else self._chromosome
        callset = allel.read_vcf(vcf, region=f"{chrval}:{self._start}-{self._end}")
        if callset is None or len(callset['variants/POS']) == 0:
            print(f"No variants found for transcript {self.id} in VCF {vcf}.")
            return
        if samples is not None:
            callset, sampleIDs, sampleLOCs = _sort_vcf(callset, samples)
            self.samples = sampleIDs
            self.locs = sampleLOCs
        if filter is not None:
            sampleIDs = self.samples if self.samples is not None else callset['samples']
            filter_callset = allel.read_vcf(filter, region=f'{chrval}:{self._start}-{self._end}',
                                            samples=sampleIDs)
            keeppos = np.isin(callset['variants/POS'], filter_callset['variants/POS'])
            for key in callset.keys():
                if key.startswith('variants/') or key.startswith('calldata/'):
                    callset[key] = callset[key][keeppos]
        cds_seq, cds_seq_array = get_nucleotide_sequences(callset, self.coding_seq)
        wt_AA_seq, aa_seq_array = get_aa_sequences(cds_seq_array, cds_seq, fasta_check=protein_fasta)
        sitesval = mean_ss_sites(cds_seq_array, wt_AA_seq)
        synarr, nonarr = identify_ss_ns_sites(cds_seq_array, cds_seq, aa_seq_array, wt_AA_seq)
        self.samples = samples if samples is not None else callset['samples'].tolist()
        self.variants = Variants(
            callset=callset,
            wt_nt_seq=cds_seq,
            wt_aa_seq=wt_AA_seq,
            cds_seq_array=cds_seq_array,
            aa_seq_array=aa_seq_array,
            synarr=synarr,
            nonarr=nonarr,
            mean_nssites=sitesval[1],
            mean_ssites=sitesval[0],
            locs=self.locs,
        )
        return self.variants

    def calculate_statistics(self):
        """Calculate statistics for a given transcript."""
        if self.variants is None:
            print(f"No variants loaded for transcript {self.id}. Cannot calculate statistics.")
            return {}
        stat_flags = {k: v for k, v in self.statistics.items() if isinstance(v, bool)} \
                     if isinstance(self.statistics, dict) else {s: True for s in self.statistics}
        self.variants.calculate_statistics(stat_flags)
        self.statistics = self.variants.statistics
        self.pairwise_fst = self.variants.pairwise_fst
        return self.statistics


class Variants:
    def __init__(self, callset, wt_nt_seq, wt_aa_seq, cds_seq_array, aa_seq_array,
                 synarr, nonarr, mean_nssites, mean_ssites, locs=None):
        self.callset = callset
        self.wt_nt_seq = wt_nt_seq
        self.wt_aa_seq = wt_aa_seq
        self.cds_seq_array = cds_seq_array
        self.aa_seq_array = aa_seq_array
        self.synarr = synarr
        self.nonarr = nonarr
        self.mean_nssites = mean_nssites
        self.mean_ssites = mean_ssites
        self.locs = locs
        self.statistics = pd.DataFrame(
            index=['pi', 'theta', 'tajD', 'Fst'], columns=['gene', 'cds', 'aa', 'ss', 'ns']
        )
        self.pairwise_fst = None

    def __repr__(self):
        n_pos = len(self.positions) if self.callset is not None else 0
        n_samples = self.cds_seq_array.shape[1] if self.cds_seq_array is not None else 0
        n_variants = sum(allel.GenotypeArray(self.callset['calldata/GT']).sum(axis=1).sum(axis=1) > 0) if self.cds_seq_array is not None else 0
        return (
            f'Variants: {n_pos} positions | {n_variants} variant sites |  samples: {n_samples}'
            f'  |  locs: {"Yes" if self.locs is not None else "No"}\n'
            f'  WT nt length: {len(self.wt_nt_seq)}  |  WT aa length: {len(self.wt_aa_seq)}\n'
            f'  Mean S sites: {self.mean_ssites:.1f}  |  Mean NS sites: {self.mean_nssites:.1f}'
        )

    @property
    def gt_array(self):
        return allel.GenotypeArray(self.callset['calldata/GT'])

    @property
    def positions(self):
        return self.callset['variants/POS']

    def calculate_statistics(self, stat_flags):
        """Calculate popgen statistics given a dict of flags.

        Parameters
        ----------
        stat_flags : dict
            Keys are statistic names ('pi', 'theta', 'tajD', 'Fst', 'pairwiseFst'),
            values are booleans indicating whether to calculate each.

        Updates self.statistics in-place — only rows for enabled flags are written,
        so previously calculated statistics are preserved across repeated calls.
        Pairwise Fst is stored separately in self.pairwise_fst.
        Returns (self.statistics, self.pairwise_fst).
        """
        cds_seq_array = convert_to_binaryarray(self.cds_seq_array, self.wt_nt_seq)
        aa_array = convert_to_binaryarray(self.aa_seq_array, self.wt_aa_seq)
        ss_array = convert_to_binaryarray(self.synarr, np.repeat('', len(self.wt_nt_seq)))
        ns_array = convert_to_binaryarray(self.nonarr, np.repeat('', len(self.wt_nt_seq)))
        if stat_flags.get('pi'):
            self.statistics.loc['pi'] = {
                'gene': calc_pi(self.gt_array, len(self.positions)),
                'cds': calc_pi(cds_seq_array, len(self.wt_nt_seq)),
                'aa': calc_pi(aa_array, self.mean_nssites),
                'ss': calc_pi(ss_array, self.mean_ssites) if ss_array is not None else 0,
                'ns': calc_pi(ns_array, self.mean_nssites) if ns_array is not None else 0,
            }
        if stat_flags.get('theta'):
            self.statistics.loc['theta'] = {
                'gene': calc_theta(self.gt_array, len(self.positions)),
                'cds': calc_theta(cds_seq_array, len(self.wt_nt_seq)),
                'aa': calc_theta(aa_array, self.mean_nssites),
                'ss': calc_theta(ss_array, self.mean_ssites) if ss_array is not None else 0,
                'ns': calc_theta(ns_array, self.mean_nssites) if ns_array is not None else 0,
            }
        if stat_flags.get('tajD'):
            self.statistics.loc['tajD'] = {
                'gene': calc_taj(self.gt_array, len(self.positions)),
                'cds': calc_taj(cds_seq_array, len(self.wt_nt_seq)),
                'aa': calc_taj(aa_array, self.mean_nssites),
                'ss': calc_taj(ss_array, self.mean_ssites) if ss_array is not None else 0,
                'ns': calc_taj(ns_array, self.mean_nssites) if ns_array is not None else 0,
            }
        if stat_flags.get('Fst') and self.locs is not None:
            if np.unique(self.locs, axis=0).shape[0] == 1:
                warnings.warn("Only one sampling location. Returning NaN for Fst.")
                self.statistics.loc['Fst'] = {
                    'gene': np.nan,
                    'cds': np.nan,
                    'aa': np.nan,
                    'ss': np.nan,
                    'ns': np.nan
                }
            else:
                self.statistics.loc['Fst'] = {
                    'gene': calc_fst_wc(self, self.gt_array),
                    'cds': calc_fst_wc(self, cds_seq_array),
                    'aa': calc_fst_wc(self, aa_array),
                    'ss': calc_fst_wc(self, ss_array) if ss_array is not None else 0,
                    'ns': calc_fst_wc(self, ns_array) if ns_array is not None else 0,
                }
        if stat_flags.get('pairwiseFst') and self.locs is not None:
            self.pairwise_fst = self._pairwise_fst_df(cds_seq_array, aa_array, ss_array, ns_array)
        return self.statistics, self.pairwise_fst

    def _pairwise_fst_df(self, cds_seq_array, aa_array, ss_array=None, ns_array=None):
        """Calculate pairwise Hudson's Fst across all sampling locations."""
        gene_fst = triang2df_fst(calc_fst_pairwise(self, self.gt_array))
        cds_fst = triang2df_fst(calc_fst_pairwise(self, cds_seq_array))
        aa_fst = triang2df_fst(calc_fst_pairwise(self, aa_array))
        gene_fst = gene_fst.rename(columns={'fst': 'gene_fst'})
        cds_fst = cds_fst.rename(columns={'fst': 'cds_fst'})
        aa_fst = aa_fst.rename(columns={'fst': 'aa_fst'})
        df = pd.merge(gene_fst, cds_fst, on=['loc1', 'loc2'])
        df = pd.merge(df, aa_fst, on=['loc1', 'loc2'])
        if ss_array is not None:
            ss_fst = triang2df_fst(calc_fst_pairwise(self, ss_array))
            ss_fst = ss_fst.rename(columns={'fst': 'ss_fst'})
            df = pd.merge(df, ss_fst, on=['loc1', 'loc2'])
        if ns_array is not None:
            ns_fst = triang2df_fst(calc_fst_pairwise(self, ns_array))
            ns_fst = ns_fst.rename(columns={'fst': 'ns_fst'})
            df = pd.merge(df, ns_fst, on=['loc1', 'loc2'])
        return df
