import statistics
import pandas as pd
from matplotlib.pyplot import fill
import numpy as np
import argparse
from Bio import Entrez, SeqIO, codonalign
from Bio.Seq import Seq
import gffutils
import allel
from allel.util import ignore_invalid
import time, os, itertools, json

def _parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Calculate popgen statistics for a gene in a VCF file")
    parser.add_argument('--gene', type=str, help='Gene name to analyze', required=True)
    parser.add_argument('--transcript', type=str, help='Transcript ID from gene to analyze (optional)', default=None)
    parser.add_argument('--vcf', type=str, help='Path to the VCF file', required=True)
    parser.add_argument('--filter', type=str, help='Path to the filter VCF file (optional)', default=None)
    parser.add_argument('--annotation', help='Path to genome annotation DB (created by parse_gff.py)', type=str, required=True)
    parser.add_argument('--fasta', type=str, help='Path to the reference genome FASTA file', required=True)
    parser.add_argument('--proteinfasta', type=str, help='Path to the reference protein FASTA file (for checking amino acid sequences)', default=None)
    parser.add_argument('--metadata', type=str, help='Path to metadata file (optional)', default=None)
    parser.add_argument('--chromosome', type=str, help='Chromosome of the gene', default=None)
    parser.add_argument('--start', type=int, help='Start position of the gene', default=None)
    parser.add_argument('--end', type=int, help='End position of the gene', default=None)
    parser.add_argument('--pi', default=True, action='store_false', help='disable calculation of nucleotide diversity (pi).')
    parser.add_argument('--theta', default=True, action='store_false', help='disable calculation of Watterson\'s theta.')
    parser.add_argument('--tajD', default=True, action='store_false', help='disable calculation of Tajima\'s D.')
    parser.add_argument('--Fst', default=False, action='store_true', help='Calculate pairwise Fst between samples. Default is False.')
    parser.add_argument('--output', type=str, default=None, help='Save statistics to this file if provided. If file exists, append to it, if not, create a new file.')
    parser.add_argument('--print', default=True, action='store_false', help='disable print statistics to the console.')
    return parser.parse_args()

class Gene:
    def __init__(self, name, chromosome=None, start=None, end=None, statistics=['pi','tajD','theta'], samples=None,
                 vcf=None, annotation=None, fasta=None):
        self._name = name
        self._chromosome = chromosome
        self._start = start
        self._end = end
        self._length = self._end - self._start + 1 if self._start is not None and self._end is not None else None
        self._gc_content = None # GC content will be calculated later
        self._samples = samples
        self._locs = None
        self.transcripts = None
        self.statistics = statistics
        self.vcf = None
        self.annotation = None
        self.fasta = None

    @property
    def samples(self, samples=None):
        if samples is not None:
            self._samples = samples
        if type(self._samples) is pd.DataFrame:
            return self._samples
        elif type(self._samples) is list or type(self._samples) is np.ndarray:
            return pd.DataFrame(self._samples, columns=['sample_id'])
        elif os.path.isfile(self._samples):
            self._samples = pd.read_csv(self._samples, sep='\t')
            return self._samples
    
    @property
    def name(self):
        return self._name

    def fetch_gene_coordinates(self, annotation, fasta):
        """Fetch gene coordinates from a GFF database generated by parse_gff.py."""
        self.annotation = annotation
        self.fasta = fasta
        db = gffutils.FeatureDB(annotation, keep_order=True)
        feature = db[self._name]
        self.chromosome = feature.chrom
        self.start = feature.start
        self.end = feature.end
        self.length = self.end - self.start + 1
        # calculate GC content
        seq = feature.sequence(fasta, use_strand=False)
        self.gc_content = (seq.count('G') + seq.count('C')) / len(seq) if len(seq) > 0 else 0
        return feature.chrom, feature.start, feature.end
    
    def fetch_gene_transcripts(self, transcriptID='mRNA'):
        """Fetch transcripts for a given gene from a GFF database."""
        db = gffutils.FeatureDB(self.annotation, keep_order=True)
        transcripts = list(db.children(self.name, featuretype=transcriptID))
        self.transcripts = tuple([Transcript(id=tx.id, gene=self.name, annotation=self.annotation, fasta=self.fasta,
                                        chromosome=tx.chrom, start=tx.start, end=tx.end, statistics=self.statistics, vcf=self.vcf)
                                  for tx in transcripts])
        return transcripts

    def load_variation(self, vcf, samples=None, filter=None, protein_fasta=None, locs=None):
        """Fetch variants for all transcripts of a given gene from a VCF file."""
        self.vcf = vcf
        for tx in self.transcripts:
            tx.load_variation(vcf, samples=samples, filter=filter, protein_fasta=protein_fasta, locs=locs)
        self._samples = self.transcripts[0].samples
        self._locs = self.transcripts[0].locs
        return self._samples, self._locs

    def calculate_statistics(self):
        """Calculate statistics for all transcripts of a given gene."""
        stats = {}
        for tx in self.transcripts:
            tx_stats = tx.calculate_statistics()
            stats[tx.id] = tx_stats
        self.statistics = stats
        return stats

class Transcript:
    def __init__(self, id, gene, annotation, fasta, vcf, chromosome=None, start=None, end=None, statistics=None):
        db = gffutils.FeatureDB(annotation, keep_order=True)
        cds = list(db.children(id, featuretype='CDS'))
        self._cds_id = [c.id for c in cds]
        self._cds_start = [c.start for c in cds]
        self._cds_end = [c.end for c in cds]
        self._cds_seq = [c.sequence(fasta, use_strand=False) for c in cds]
        self._cds_strand = cds[0].strand if cds else None
        self.id = id
        self._gene = gene
        self._chromosome = chromosome
        self._start = start
        self._end = end
        # nucleotide sequence
        if self._cds_strand == '-':
            cds_seq = [str(Seq(x).reverse_complement()) for x in self._cds_seq]
            self.NTseq = np.fromiter("".join(cds_seq), dtype='U1') # numpy array of coding sequence
            self._cds_positions = np.concatenate([np.flip(np.arange(s, e+1)) for s, e in zip(self._cds_start, self._cds_end)])
        else:
            self.NTseq = np.fromiter("".join(self._cds_seq), dtype='U1') # numpy array of coding sequence
            self._cds_positions = np.concatenate([np.arange(s, e+1) for s, e in zip(self._cds_start, self._cds_end)])
        self.cds_length = len(self.NTseq)
        self.AAseq = np.fromiter(codonalign.codonseq.CodonSeq("".join(self.NTseq)).translate(), dtype='U1')
        self.samples = None
        self.locs = None
        self.variants = {}
        self.statistics = statistics
        self.vcf = vcf
        self.annotation = annotation
        self.fasta = fasta
    
    def load_variation(self, vcf, samples=None, filter=None, protein_fasta=None, locs=False):
        """Fetch variants for a given transcript from a VCF file."""
        self.vcf = vcf
        chrval = self._chromosome.split('_')[-1] if '_' in self._chromosome else self._chromosome
        callset = allel.read_vcf(vcf, region=f"{chrval}:{self._start}-{self._end}")
        if callset is None or len(callset['variants/POS']) == 0:
            print(f"No variants found for transcript {self.id} in VCF {vcf}.")
            return
        if samples is not None:
            callset, sampleIDs, sampleLOCs = self._sort_vcf(callset, samples, locs=locs)
            self.samples = sampleIDs
            self.locs = sampleLOCs
        if filter is not None:
            # Load the filter VCF file and apply it to the callset
            filter_callset = allel.read_vcf(filter, region=f'{chrval}:{self._start}-{self._end}', samples=sampleIDs)
            keeppos = np.isin(callset['variants/POS'], filter_callset['variants/POS'])
            for key in callset.keys():
                if key.startswith('variants/') or key.startswith('calldata/'):
                    callset[key] = callset[key][keeppos]
        cds_seq_array = get_nucleotide_sequences(callset, self._cds_positions, self.NTseq, self._cds_strand)
        aa_seq_array = get_aa_sequences(cds_seq_array, self.NTseq, fasta_check=protein_fasta)
        sitesval = mean_ss_sites(cds_seq_array, self.AAseq)
        synarr, nonarr = identify_ss_ns_sites(cds_seq_array, self.NTseq, aa_seq_array, self.AAseq)
        self.samples = samples if samples is not None else callset['samples'].tolist()
        self.variants = {
            'callset': callset,
            'cds_seq_array': cds_seq_array,
            'aa_seq_array': aa_seq_array,
            'synarr': synarr,
            'nonarr': nonarr,
            'mean_nssites': sitesval[1],
            'mean_ssites': sitesval[0]
            }
        return self.variants

    def calculate_statistics(self):
        """Calculate statistics for a given transcript."""
        cds_seq_array = convert_to_binaryarray(self.variants['cds_seq_array'], 
                                                self.NTseq)
        aa_array = convert_to_binaryarray(self.variants['aa_seq_array'], 
                                               self.AAseq)
        ss_array = convert_to_binaryarray(self.variants['synarr'],
                                           np.repeat('', len(self.NTseq)))
        ns_array = convert_to_binaryarray(self.variants['nonarr'],
                                           np.repeat('', len(self.NTseq)))
        stats = {}
        if self.variants is None or len(self.variants) == 0:
            print(f"No variants loaded for transcript {self.id}. Cannot calculate statistics.")
            return stats
        if 'pi' in self.statistics:
            stats['pi_gene'] = calc_pi(allel.GenotypeArray(self.variants['callset']['calldata/GT']), 
                                       len(self.variants['callset']['variants/POS']))
            stats['pi_nt'] = calc_pi(cds_seq_array, self.cds_length)
            stats['pi_aa'] = calc_pi(aa_array, np.sum(self.variants['mean_nssites']))
            stats['pi_syn'] = calc_pi(ss_array, np.sum(self.variants['mean_ssites']))
            stats['pi_non'] = calc_pi(ns_array, np.sum(self.variants['mean_nssites']))
        if 'theta' in self.statistics:
            stats['theta_gene'] = calc_theta(allel.GenotypeArray(self.variants['callset']['calldata/GT']), 
                                       len(self.variants['callset']['variants/POS']))
            stats['theta_nt'] = calc_theta(cds_seq_array, self.cds_length)
            stats['theta_aa'] = calc_theta(aa_array, np.sum(self.variants['mean_nssites']))
            stats['theta_syn'] = calc_theta(ss_array, np.sum(self.variants['mean_ssites']))
            stats['theta_non'] = calc_theta(ns_array, np.sum(self.variants['mean_nssites']))
        if 'tajD' in self.statistics:
            stats['tajD_gene'] = calc_taj(allel.GenotypeArray(self.variants['callset']['calldata/GT']), 
                                       len(self.variants['callset']['variants/POS']))
            stats['tajD_nt'] = calc_taj(cds_seq_array, self.cds_length)
            stats['tajD_aa'] = calc_taj(aa_array, np.sum(self.variants['mean_nssites']))
            stats['tajD_syn'] = calc_taj(ss_array, np.sum(self.variants['mean_ssites']))
            stats['tajD_non'] = calc_taj(ns_array, np.sum(self.variants['mean_nssites']))
        if 'fst' in self.statistics and self.locs is not None:
            fstmat_nt = calc_fst_pairwise(self, cds_seq_array)
            fstmat_aa = calc_fst_pairwise(self, aa_array)
            fstmat_syn = calc_fst_pairwise(self, ss_array)
            fstmat_non = calc_fst_pairwise(self, ns_array)
            stats['fst_nt'] = triang2df_fst(fstmat_nt)
            stats['fst_aa'] = triang2df_fst(fstmat_aa)
            stats['fst_syn'] = triang2df_fst(fstmat_syn)
            stats['fst_non'] = triang2df_fst(fstmat_non)
        self.statistics = stats
        return stats

    def _sort_vcf(self, callset, samples, locs=False):
        """Sort VCF file by samples"""
        sampleIDs = samples['sample_id'].tolist()
        sampleIDs = np.array(sampleIDs)
        sample_indices = np.array([[-1, np.nan] if len(np.where(callset['samples'] == i)[0]) == 0 # remove if no match in VCF
                        else [[-1 if len(np.where(sampleIDs == i)[0]) == 0 # remove if no match in metadata
                        else np.where(sampleIDs == i)[0][0]][0], np.where(callset['samples'] == i)[0][0]]
                        for i in sampleIDs])
        sample_indices = sample_indices[sample_indices[:,0] != -1]
        sample_indices = sample_indices.astype(int)
        sampleIDs = sampleIDs[sample_indices[:,0]]
        callset['calldata/GT'] = allel.GenotypeArray(callset['calldata/GT'][:,sample_indices[:,1],:])
        callset['samples'] = sampleIDs
        # double check that genotypes match
    # assert (genotypes[:,0:1] == allel.GenotypeArray(callset['calldata/GT'][:,sample_indices[0:1,1],:])).all()
        # re-sort metadata
        samples.index = samples['sample_id']
        samples = samples.reindex(sampleIDs)
        if locs:
            assert ('latitude' in samples.columns and 'longitude' in samples.columns) or ('x' in samples.columns and 'y' in samples.columns), "Metadata file must contain 'latitude' and 'longitude' or 'x' and 'y' columns for location data."
            try: 
                sampleLOCs = np.array([samples['longitude'], samples['latitude']]).T
            except:
                sampleLOCs = np.array([samples['x'], samples['y']]).T
        else:
            sampleLOCs = None
        return(callset, sampleIDs, sampleLOCs)
        

# Functions for dealing with nucleotide and amino acid sequences
##########################################################


def count_sites(cds_seq, aa_seq):
    """ 
    calculate number of silent and non-silent sites in a coding sequence 
    returns array with shape (n_codons, 2) where:
    - first column is the number of silent sites per codon (divided by 3)
    - second column is the number of non-silent sites per codon (divided by 3)
    stop codons are excluded from the count
    """
    codons = np.split(cds_seq, len(aa_seq))
    codon_ss_sites = np.empty((len(codons), 2), dtype=float)
    with open('scripts/codontable.json', 'r') as f:
        codontab = json.load(f)

    for i, codon in enumerate(codons):
        silent_sites = 0
        non_silent_sites = 0
        originalAA = codontab[''.join(codon)]
        assert originalAA == aa_seq[i], f"Original AA {originalAA} does not match expected {aa_seq[i]} at position {i}."
        states = ["A", "C", "G", "T"]
        for codonpos in range(3):
            for state in states:
                new_codon = codon.copy()
                new_codon[codonpos] = state
                if ''.join(new_codon) == ''.join(codon):
                    continue
                newAA = codontab[''.join(new_codon)]
                if newAA == originalAA:
                    silent_sites += 1
                elif newAA == '*':
                    # stop codon, we don't count these as silent or non-silent
                    continue
                else:
                    non_silent_sites += 1
        codon_ss_sites[i][0] = silent_sites/3
        codon_ss_sites[i][1] = non_silent_sites/3
    return codons, codon_ss_sites

def mean_ss_sites(cds_seq_array, aa_seq):
    """
    calculate mean number of silent and non-silent sites across all sequences
    """
    ss_sites = np.empty((len(cds_seq_array[0,:]), 2), dtype=float)
    for i in range(len(cds_seq_array[0,:])):
        for j in [0, 1]:
            aa_seq_arr = codonalign.codonseq.CodonSeq("".join(cds_seq_array[:, i, j])).translate()
            c_a, s_a, = count_sites(cds_seq_array[:, i, j], aa_seq_arr)
            ss_sites[i, :] = np.sum(s_a, axis=0)
    mean_silent_sites = np.mean(ss_sites[:, 0])
    mean_non_silent_sites = np.mean(ss_sites[:, 1])
    return mean_silent_sites, mean_non_silent_sites

def get_nucleotide_sequences(callset, coding_seq_positions, coding_seq, coding_strand):
    """get coding sequences from a VCF file and create an array of nucleotide sequences."""
    positions = callset['variants/POS']
    positionmask = np.repeat(False, len(positions))
    positionmask[np.isin(positions, coding_seq_positions)] = True
    positions = positions[positionmask]
    alt = callset['variants/ALT'][positionmask]  # alternate alleles for variant positions
    gt = allel.GenotypeArray(callset['calldata/GT'][positionmask]) # genotype calls for variant positions
    complement_dict = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C', 'N': 'N'}
    assert(np.all(coding_seq[0:3] == ['A','T','G'])) # ensure start codon
    cds_seq_array = np.tile(coding_seq, (2, gt.shape[1], 1)).T
    variant_cds_positions, variant_cds_index, variant_position_index = np.intersect1d(coding_seq_positions, positions, return_indices=True) # find intersection of CDS and variant positions
    for vcp, vci, vpi in zip(variant_cds_positions, variant_cds_index, variant_position_index):
        for i in np.unique(gt[vpi]):
            if i > 0:
                if coding_strand == '-':
                    altNT = complement_dict[alt[vpi][i-1]] 
                else:
                    altNT = alt[vpi][i-1]
                assert(altNT != coding_seq[vci]) # ensure alternate allele is not the same as the reference
                cds_seq_array[vci][gt[vpi]==i] = altNT    
    return cds_seq_array

def get_aa_sequences(cds_seq_array, cds_seq, ID=None, fasta_check=None):
    """Translate array of coding sequences into protein sequences."""
    wt_AA_seq = np.fromiter(codonalign.codonseq.CodonSeq("".join(cds_seq)).translate(), dtype='U1')  # wild-type coding sequence
    aa_array = np.apply_along_axis(lambda x: np.fromiter(codonalign.codonseq.CodonSeq("".join(x)).translate(), dtype='U1'), 0, cds_seq_array) # array of AA sequences (translated)
    if fasta_check:
        pdct = SeqIO.index(fasta_check, 'fasta')
        assert(np.all(np.fromiter(pdct[ID.replace('R','P')].seq, dtype='U1') == wt_AA_seq[:-1]))
    return aa_array

def identify_ss_ns_sites(cds_seq_array, cds_seq, aa_array, wt_AA_seq):
    """Identify synonymous and non-synonymous mutations in the array of coding sequences."""
    codon_array = np.split(cds_seq, len(cds_seq) // 3)
    synonymous_array = np.zeros(cds_seq_array.shape, dtype='U10')
    nonsynonymous_array = np.zeros(cds_seq_array.shape, dtype='U10')
    for i in range(len(aa_array[0, :, 0])):
        for j in [0, 1]:
            codons = np.split(cds_seq_array[:, i, j], len(cds_seq)//3)
            mutcodons = np.where([codons[x] != codon_array[x] for x in range(len(codon_array))])
            mutloci = mutcodons[0]*3 + mutcodons[1]  # calculate the mutation loci in the codon array
            nscodons = np.where(aa_array[:, i, j] != wt_AA_seq)[0]
            #print(np.isin(mutcodons[0], nscodons))
            nsloci = mutloci[np.isin(mutcodons[0], nscodons)]
            sscodons = np.array([x for x in mutcodons[0] if x not in nscodons])
            ssloci = mutloci[np.isin(mutcodons[0], sscodons)]
            if len(ssloci) > 0:
                synonymous_array[ssloci, i, j] = cds_seq_array[ssloci, i, j]
            if len(nsloci) > 0:
                nonsynonymous_array[nsloci, i, j] = cds_seq_array[nsloci, i, j]
    return synonymous_array, nonsynonymous_array

def convert_to_binaryarray(sequence_array, wt_sequence):
    """ convert nt or amino acid sequences to binary array format for genotype calls """
    for i in range(sequence_array.shape[0]):
        wt_val = wt_sequence[i]
        all_val = np.unique(sequence_array[i, :, :])
        all_val = np.roll(all_val, -1*np.where(all_val == wt_val)[0])
        for a in range(len(all_val)):
            val_id = all_val[a]
            msk = sequence_array[i, :, :] == val_id
            sequence_array[i, msk] = a  # replace amino acid with its index
    sequence_array = sequence_array.astype(int)  # convert to integer type
    sequence_array = allel.GenotypeArray(sequence_array)
    nonvariant_mask = sequence_array.count_hom_ref(axis=1) < sequence_array.shape[1]
    sequence_array = sequence_array[nonvariant_mask]
    if len(sequence_array) == 0:
        return None
    else:
        return sequence_array

def triang2df_fst(mtx1):
    mtx1 = mtx1.where(np.triu(np.ones(mtx1.shape)).astype(bool))
    mtx1 = mtx1.stack().reset_index()
    mtx1.columns = ['loc1', 'loc2', 'fst']
    mtx1 = mtx1.dropna()
    return mtx1

##################################################################
# Functions for calculating statistics
##################################################################

def calc_pi(sequence_array, nsites):
    """Calculate nucleotide diversity (pi) for a given sequence array."""
    # manually calculate pi, stolen from scikit-allel
    if sequence_array is None or len(sequence_array) == 0:
        return 0
    else:
        ac = sequence_array.count_alleles()
        an = np.sum(ac, axis=1)
        n_pairs = an * (an - 1) / 2
        n_same = np.sum(ac * (ac - 1) / 2, axis=1) 
        n_diff = n_pairs - n_same
        mpd = n_diff / n_pairs
        mpd_sum = np.sum(mpd)
        pi = mpd_sum / nsites if nsites > 0 else 0
        return pi

def calc_theta(sequence_array, nsites):
    """Calculate Watterson's theta (theta hat per base) for a given sequence array."""
    # manually calculate Watterson's estimator (theta hat per base)
    # stolen from scikit-allel
    if sequence_array is None or len(sequence_array) == 0:
        return 0
    else:
        ac = sequence_array.count_alleles()
        # count segregating variants
        S = ac.count_segregating()
        # assume number of chromosomes sampled is constant for all variants
        n = ac.sum(axis=1).max()
        # (n-1)th harmonic number
        a1 = np.sum(1 / np.arange(1, n))
        # calculate absolute value
        theta_hat_w_abs = S / a1
        # calculate value per base
        theta_hat_w = theta_hat_w_abs / nsites if nsites > 0 else 0
        return theta_hat_w

def calc_taj(sequence_array, nsites, min_sites=3):
    """Manually calculate Tajima's D."""
    # stolen from scikit-allel
    if sequence_array is None or len(sequence_array) == 0:
        return 0
    ac = sequence_array.count_alleles()
    S = ac.count_segregating()
    if S < min_sites:
        return np.nan
    # assume number of chromosomes sampled is constant for all variants
    n = ac.sum(axis=1).max()
    # (n-1)th harmonic number
    a1 = np.sum(1 / np.arange(1, n))
    # calculate Watterson's theta (absolute value)
    theta_hat_w_abs = S / a1
    # calculate mean pairwise difference
    an = np.sum(ac, axis=1)
    n_pairs = an * (an - 1) / 2
    n_same = np.sum(ac * (ac - 1) / 2, axis=1) 
    n_diff = n_pairs - n_same
    mpd = n_diff / n_pairs
    # calculate theta_hat pi (sum differences over variants)
    theta_hat_pi_abs = np.sum(mpd)
    # N.B., both theta estimates are usually divided by the number of
    # (accessible) bases but here we want the absolute difference
    d = theta_hat_pi_abs - theta_hat_w_abs
    # calculate the denominator (standard deviation)
    a2 = np.sum(1 / (np.arange(1, n)**2))
    b1 = (n + 1) / (3 * (n - 1))
    b2 = 2 * (n**2 + n + 3) / (9 * n * (n - 1))
    c1 = b1 - (1 / a1)
    c2 = b2 - ((n + 2) / (a1 * n)) + (a2 / (a1**2))
    e1 = c1 / a1
    e2 = c2 / (a1**2 + a2)
    d_stdev = np.sqrt((e1 * S) + (e2 * S * (S - 1)))
    # finally calculate Tajima's D
    D = d / d_stdev if d_stdev > 0 else np.nan

    return D

def calc_fst_btwn(gene, seqs, loc1, loc2):
    """Calculate Hudson's Fst between two locations."""
    locs = gene.locs
    assert sum(seqs.count_hom_ref(axis=1) == seqs.shape[1]) == 0 # no all-ref variants
    ind1 = np.where((locs == loc1).all(1))[0]
    ind2 = np.where((locs == loc2).all(1))[0]
    ac1 = seqs[:, ind1].count_alleles()
    ac2 = seqs[:, ind2].count_alleles()
    n, d = allel.hudson_fst(ac1, ac2, fill=np.nan)
    with np.errstate(invalid='ignore'):
        fst = np.nansum(n) / np.nansum(d)
    return fst

def calc_fst_pairwise(gene, seqs):
    """Calculate pairwise Fst between all locations."""
    locs = np.unique(gene.locs, axis=0)
    fstmat = pd.DataFrame(index=[tuple(i) for i in locs], columns=[tuple(i) for i in locs])
    for i, j in itertools.combinations(locs, 2):
        itup = tuple(i)
        jtup = tuple(j)
        fst = calc_fst_btwn(gene, seqs, i, j)
        fstmat[itup][jtup] = fst
        fstmat[jtup][itup] = fst
    return fstmat 

###################################################################

def main():
    """Popgen statistics for a gene..."""
    args = _parse_args()
    if not args.vcf or not args.gene or not args.annotation or not args.fasta:
        raise ValueError("Please provide all required arguments: --vcf, --gene, --annotation, --fasta")
    GENE = Gene(name=args.gene, chromosome=args.chromosome, start=args.start, end=args.end,
                statistics={'pi':args.pi,
                            'theta':args.theta,
                            'tajD':args.tajD,
                            'Fst':args.Fst})
    
if __name__ == "__main__":
    start_time = time.time()
    main()
    end_time = time.time()
    print(f"Execution time: {end_time - start_time:.2f} seconds")