from matplotlib.pyplot import fill
import numpy as np
import argparse
from Bio import Entrez, SeqIO, codonalign
from Bio.Seq import Seq
import gffutils
import allel
from allel.util import ignore_invalid
import time, os

parser = argparse.ArgumentParser(description="Fetch gene coordinates and statistics from a GFF database.")
parser.add_argument('--name', type=str, required=True, help='Gene name to fetch coordinates for.')
parser.add_argument('--annotation', type=str, required=True, help='Path to the GFF database file.')
parser.add_argument('--fasta', type=str, required=True, help='Path to the FASTA file for sequence retrieval.')
args = parser.parse_args()

def fetch_gene_coordinates(name, annotation, fasta):
    """Fetch gene coordinates from a GFF database generated by parse_gff.py."""
    db = gffutils.FeatureDB(annotation, keep_order=True)
    feature = db[name]
    chromosome = feature.chrom
    start = feature.start
    end = feature.end
    length = end - start + 1
    # calculate GC content
    seq = feature.sequence(fasta, use_strand=False)
    gc_content = (seq.count('G') + seq.count('C')) / len(seq) if len(seq) > 0 else 0
    return chromosome, start, end, length, gc_content

chromosome, start, end, length, gc_content = fetch_gene_coordinates(
    name=args.name,
    annotation=args.annotation,
    fasta=args.fasta
)

print(f"{args.name}\t{chromosome}\t{start}\t{end}\t{length}\t{gc_content:.5f}")
