"""
Calculate popgen statistics for a given gene in a VCF file

Required input:
- VCF file
- Gene annotation file (GFF3) database constructed with gffutils 
    - can be created with parse_gff.py
- Gene name
- Reference genome (FASTA)

Calculates pi, theta, and Tajima's D for each gene transcript considering
- the whole gene
- the coding sequence
- the amino acid sequence
- variants at synonymous sites
- variants at non-synonymous sites
Results are stored in the Gene object and printed to the console.
"""

import statistics
import pandas as pd
from matplotlib.pyplot import fill
import numpy as np
import argparse
from Bio import Entrez, SeqIO, codonalign
from Bio.Seq import Seq
import gffutils
import allel
from allel.util import ignore_invalid
import time, os, itertools

codontab = {
    'TCA': 'S',    # Serina
    'TCC': 'S',    # Serina
    'TCG': 'S',    # Serina
    'TCT': 'S',    # Serina
    'TTC': 'F',    # Fenilalanina
    'TTT': 'F',    # Fenilalanina
    'TTA': 'L',    # Leucina
    'TTG': 'L',    # Leucina
    'TAC': 'Y',    # Tirosina
    'TAT': 'Y',    # Tirosina
    'TAA': '*',    # Stop
    'TAG': '*',    # Stop
    'TGC': 'C',    # Cisteina
    'TGT': 'C',    # Cisteina
    'TGA': '*',    # Stop
    'TGG': 'W',    # Triptofano
    'CTA': 'L',    # Leucina
    'CTC': 'L',    # Leucina
    'CTG': 'L',    # Leucina
    'CTT': 'L',    # Leucina
    'CCA': 'P',    # Prolina
    'CCC': 'P',    # Prolina
    'CCG': 'P',    # Prolina
    'CCT': 'P',    # Prolina
    'CAC': 'H',    # Histidina
    'CAT': 'H',    # Histidina
    'CAA': 'Q',    # Glutamina
    'CAG': 'Q',    # Glutamina
    'CGA': 'R',    # Arginina
    'CGC': 'R',    # Arginina
    'CGG': 'R',    # Arginina
    'CGT': 'R',    # Arginina
    'ATA': 'I',    # Isoleucina
    'ATC': 'I',    # Isoleucina
    'ATT': 'I',    # Isoleucina
    'ATG': 'M',    # Methionina
    'ACA': 'T',    # Treonina
    'ACC': 'T',    # Treonina
    'ACG': 'T',    # Treonina
    'ACT': 'T',    # Treonina
    'AAC': 'N',    # Asparagina
    'AAT': 'N',    # Asparagina
    'AAA': 'K',    # Lisina
    'AAG': 'K',    # Lisina
    'AGC': 'S',    # Serina
    'AGT': 'S',    # Serina
    'AGA': 'R',    # Arginina
    'AGG': 'R',    # Arginina
    'GTA': 'V',    # Valina
    'GTC': 'V',    # Valina
    'GTG': 'V',    # Valina
    'GTT': 'V',    # Valina
    'GCA': 'A',    # Alanina
    'GCC': 'A',    # Alanina
    'GCG': 'A',    # Alanina
    'GCT': 'A',    # Alanina
    'GAC': 'D',    # Acido Aspartico
    'GAT': 'D',    # Acido Aspartico
    'GAA': 'E',    # Acido Glutamico
    'GAG': 'E',    # Acido Glutamico
    'GGA': 'G',    # Glicina
    'GGC': 'G',    # Glicina
    'GGG': 'G',    # Glicina
    'GGT': 'G'     # Glicina
}

class Gene:
    def __init__(self, name, chromosome=None, start=None, end=None, statistics=None):
        self.name = name
        self.chromosome = chromosome
        self.start = start
        self.end = end
        self.length = end - start + 1 if start is not None and end is not None else None
        self.gc_content = None # GC content will be calculated later
        self.samples = None
        self.locs = None
        self.transcripts = {}
        self.statistics = statistics

    def fetch_gene_coordinates(self, annotation, fasta):
        """Fetch gene coordinates from a GFF database generated by parse_gff.py."""
        db = gffutils.FeatureDB(annotation, keep_order=True)
        feature = db[self.name]
        self.chromosome = feature.chrom
        self.start = feature.start
        self.end = feature.end
        self.length = self.end - self.start + 1
        # calculate GC content
        seq = feature.sequence(fasta, use_strand=False)
        self.gc_content = (seq.count('G') + seq.count('C')) / len(seq) if len(seq) > 0 else 0
        return feature.chrom, feature.start, feature.end

    def fetch_gene_transcripts(self, annotation, transcriptID='mRNA'):
        """Fetch transcripts for a given gene from a GFF database."""
        db = gffutils.FeatureDB(annotation, keep_order=True)
        transcripts = list(db.children(self.name, featuretype=transcriptID))
        self.transcripts = {t.id: t for t in transcripts}
        return transcripts

    def fetch_coding_sequence(self, transcript, annotation, fasta, cdsID='CDS'):
        """Fetch the coding sequence for a gene from a GFF database and reference FASTA, maintaining genome-wide coordinate references."""
        db = gffutils.FeatureDB(annotation, keep_order=True)
        cds = list(db.children(transcript.id, featuretype=cdsID))
        cdsid = [c.id for c in cds]
        cdsstart = [c.start for c in cds]
        cdsend = [c.end for c in cds]
        cdsseq = [c.sequence(fasta, use_strand=False) for c in cds]
        cdsstrand = transcript.strand
        coding_seq = {
            'id': transcript.id,
            'cds_id': cdsid,
            'cds_start': cdsstart,
            'cds_end': cdsend,
            'cds_seq': cdsseq,
            'strand': cdsstrand
        }
        self.transcripts[transcript.id] = coding_seq
        return coding_seq
    
    def fetch_variation(self, vcf_file, annotation, fasta, locs=False, protein_fasta=None, samples=None, filter=None):
        """Create arrays of genotype variation data, stored in the self.transcripts dictionary as
        'sequences'."""
        # Load the VCF file
        chr = self.chromosome.split('_')[-1] # remove 'chr' prefix if present
        callset = allel.read_vcf(vcf_file, region=f'{chr}:{self.start}-{self.end}')
        if samples is not None:
            callset, sampleIDs, sampleLOCs = self._sort_vcf(callset, samples, locs=locs)
            self.samples = sampleIDs
            self.locs = sampleLOCs
        if filter:
            # Load the filter VCF file and apply it to the callset
            filter_callset = allel.read_vcf(filter, region=f'{chr}:{self.start}-{self.end}', samples=sampleIDs)
            keeppos = np.isin(callset['variants/POS'], filter_callset['variants/POS'])
            for key in callset.keys():
                if key.startswith('variants/') or key.startswith('calldata/'):
                    callset[key] = callset[key][keeppos]
        if not self.transcripts:
            # fetch transcripts if not already fetched
            print(f"Fetching transcripts for gene {self.name} on chromosome {chr}")
            self.fetch_gene_transcripts(annotation=annotation)
        transcripts = self.transcripts.values()
        for transcript in transcripts:
            if type(transcript) is not dict:
                # get coding sequence if not already fetched
                print(f"Fetching coding sequence for transcript {transcript.id}")
                coding_seq = self.fetch_coding_sequence(transcript, annotation, fasta)
                self.transcripts[transcript.id] = coding_seq
            coding_seq = self.transcripts[transcript.id]
            cds_seq, cds_seq_array = get_nucleotide_sequences(callset, coding_seq)
            wt_AA_seq, aa_array = get_aa_sequences(cds_seq_array, cds_seq, ID=transcript.id, fasta_check=protein_fasta)
            sitesval = mean_ss_sites(cds_seq_array, wt_AA_seq)
            synonymous_array, nonsynonymous_array = identify_ss_ns_sites(cds_seq_array, cds_seq, aa_array, wt_AA_seq)
            self.transcripts[transcript.id]['sequences'] = {
                'genotype_array': allel.GenotypeArray(callset['calldata/GT']),
                'positions': callset['variants/POS'],
                'wt_nt_seq': cds_seq,
                'wt_aa_seq': wt_AA_seq,
                'nt_seq_array': cds_seq_array,
                'aa_seq_array': aa_array,
                'synonymous_array': synonymous_array,
                'nonsynonymous_array': nonsynonymous_array,
            }
            self.transcripts[transcript.id]['mean_nssites'] = sitesval[1]
            self.transcripts[transcript.id]['mean_sssites'] = sitesval[0]
        return

    def calculate_statistics(self, transcriptID):
        self.statistics[transcriptID] = {}
        cds_seq_array = convert_to_binaryarray(self.transcripts[transcriptID]['sequences']['nt_seq_array'], 
                                                self.transcripts[transcriptID]['sequences']['wt_nt_seq'])
        aa_array = convert_to_binaryarray(self.transcripts[transcriptID]['sequences']['aa_seq_array'], 
                                               self.transcripts[transcriptID]['sequences']['wt_aa_seq'])
        ss_array = convert_to_binaryarray(self.transcripts[transcriptID]['sequences']['synonymous_array'],
                                           np.repeat('', len(self.transcripts[transcriptID]['sequences']['wt_nt_seq'])))
        ns_array = convert_to_binaryarray(self.transcripts[transcriptID]['sequences']['nonsynonymous_array'],
                                           np.repeat('', len(self.transcripts[transcriptID]['sequences']['wt_nt_seq'])))
        if self.statistics.get('pi'):
            self.statistics[transcriptID]['pi']= {
            'gene_pi': calc_pi(self.transcripts[transcriptID]['sequences']['genotype_array'], 
                                len(self.transcripts[transcriptID]['sequences']['positions'])),
            'cds_pi': calc_pi(cds_seq_array, len(self.transcripts[transcriptID]['sequences']['wt_nt_seq'])),
            'aa_pi': calc_pi(aa_array, self.transcripts[transcriptID]['mean_nssites']),
            'ss_pi': calc_pi(ss_array, self.transcripts[transcriptID]['mean_sssites']) if ss_array is not None else 0,
            'ns_pi': calc_pi(ns_array, self.transcripts[transcriptID]['mean_nssites']) if ns_array is not None else 0,
            }
        else:
            self.statistics[transcriptID]['pi'] = {
            'gene_pi': None,
            'cds_pi': None,
            'aa_pi': None,
            'ss_pi': None,
            'ns_pi': None
            }
        if self.statistics.get('theta'):
            self.statistics[transcriptID]['theta'] = {
            'gene_theta': calc_theta(self.transcripts[transcriptID]['sequences']['genotype_array'], 
                                len(self.transcripts[transcriptID]['sequences']['positions'])),
            'cds_theta': calc_theta(cds_seq_array, len(self.transcripts[transcriptID]['sequences']['wt_nt_seq'])),
            'aa_theta': calc_theta(aa_array, self.transcripts[transcriptID]['mean_nssites']),
            'ss_theta': calc_theta(ss_array, self.transcripts[transcriptID]['mean_sssites']) if ss_array is not None else 0,
            'ns_theta': calc_theta(ns_array, self.transcripts[transcriptID]['mean_nssites']) if ns_array is not None else 0
            }
        else:
            self.statistics[transcriptID]['theta'] = {
            'gene_theta': None,
            'cds_theta': None,
            'aa_theta': None,
            'ss_theta': None,
            'ns_theta': None
            }
        if self.statistics.get('tajD'):
            self.statistics[transcriptID]['tajD'] = {
            'gene_d': calc_taj(self.transcripts[transcriptID]['sequences']['genotype_array'], 
                                len(self.transcripts[transcriptID]['sequences']['positions'])),
            'cds_d': calc_taj(cds_seq_array, len(self.transcripts[transcriptID]['sequences']['wt_nt_seq'])),
            'aa_d': calc_taj(aa_array, self.transcripts[transcriptID]['mean_nssites']),
            'ss_d': calc_taj(ss_array, self.transcripts[transcriptID]['mean_sssites']) if ss_array is not None else 0,
            'ns_d': calc_taj(ns_array, self.transcripts[transcriptID]['mean_nssites']) if ns_array is not None else 0
        }
        else:
            self.statistics[transcriptID]['tajD'] = {
            'gene_d': None,
            'cds_d': None,
            'aa_d': None,
            'ss_d': None,
            'ns_d': None
            }
        if self.statistics.get('Fst'):
            self.statistics[transcriptID]['Fst'] = self.gene_fst(transcriptID, cds_seq_array, aa_array, ss_array, ns_array)
        else:
            self.statistics[transcriptID]['Fst'] = None


        print('gene-wide pi:', self.statistics[transcriptID]['pi']['gene_pi'], 
              'cds_pi:', self.statistics[transcriptID]['pi']['cds_pi'], 
              'aa_pi:', self.statistics[transcriptID]['pi']['aa_pi'], 
              'ss_pi:', self.statistics[transcriptID]['pi']['ss_pi'], 
              'ns_pi:', self.statistics[transcriptID]['pi']['ns_pi']) if self.statistics.get('pi') else ''
        print('gene-wide theta:', self.statistics[transcriptID]['theta']['gene_theta'], 
              'cds_theta:', self.statistics[transcriptID]['theta']['cds_theta'], 
              'aa_theta:', self.statistics[transcriptID]['theta']['aa_theta'], 
              'ss_theta:', self.statistics[transcriptID]['theta']['ss_theta'], 
              'ns_theta:', self.statistics[transcriptID]['theta']['ns_theta']) if self.statistics.get('theta') else ''
        print('gene-wide Tajima\'s D:', self.statistics[transcriptID]['tajD']['gene_d'], 
              'cds_D:', self.statistics[transcriptID]['tajD']['cds_d'], 
              'aa_D:', self.statistics[transcriptID]['tajD']['aa_d'], 
              'ss_D:', self.statistics[transcriptID]['tajD']['ss_d'], 
              'ns_D:', self.statistics[transcriptID]['tajD']['ns_d']) if self.statistics.get('tajD') else ''
        print('mean gene-wide Fst:\n', np.mean(self.statistics[transcriptID]['Fst']['gene_fst']), 'cds_fst', np.mean(self.statistics[transcriptID]['Fst']['cds_fst']), 'aa_fst:', np.mean(self.statistics[transcriptID]['Fst']['aa_fst']), 'ss_fst:', np.mean(self.statistics[transcriptID]['Fst']['ss_fst']), 'ns_fst:', np.mean(self.statistics[transcriptID]['Fst']['ns_fst'])) if self.statistics.get('Fst') else ''
        print('standard deviation of gene-wide Fst:\n', np.std(self.statistics[transcriptID]['Fst']['gene_fst']), 'cds_fst', np.std(self.statistics[transcriptID]['Fst']['cds_fst']), 'aa_fst:', np.std(self.statistics[transcriptID]['Fst']['aa_fst']), 'ss_fst:', np.std(self.statistics[transcriptID]['Fst']['ss_fst']), 'ns_fst:', np.std(self.statistics[transcriptID]['Fst']['ns_fst'])) if self.statistics.get('Fst') else ''
        return

    def save_to_df(self, transcriptID, output_file='stats_output.txt', append=True):
        """Print statistics to a file."""
        if self.statistics[transcriptID]['Fst'] is not None:
            # save Fst dataframe to separate file
            fst_df = self.statistics[transcriptID]['Fst']
            fst_df.to_csv(output_file.replace('.txt', f'_{transcriptID}_Fst.txt'), sep='\t', index=False)
        if append:
            with open(output_file, 'a') as f:
                f.write(f'{self.name}\t{self.chromosome}\t{transcriptID}\t{self.length}\t{self.gc_content}\t')
                for K in self.statistics[transcriptID].keys():
                    if K == 'Fst':
                        continue
                    for L in self.statistics[transcriptID][K].values():
                        f.write(f'{L}\t')
                f.write('\n')
        else:
            with open(output_file, 'w') as f:
                # write header
                f.write(f"Gene\tChromosome\tTranscript\tLength\tGC_Content\t")
                for K in self.statistics[transcriptID].keys():
                    if K == 'Fst':
                        continue
                    for L in self.statistics[transcriptID][K].keys():
                        f.write(f'{L}\t')
                f.write('\n')
                # write data
                f.write(f'{self.name}\t{self.chromosome}\t{transcriptID}\t{self.length}\t{self.gc_content}\t')
                for K in self.statistics[transcriptID].keys():
                    if K == 'Fst':
                        continue
                    for L in self.statistics[transcriptID][K].values():
                        f.write(f'{L}\t')
                f.write('\n')
        return


    def gene_fst(self, transcriptID, cds_seq_array, aa_array, ss_array=None, ns_array=None):
        """Calculate gene-wide Fst statistics."""
        gene_fst = calc_fst_pairwise(self, self.transcripts[transcriptID]['sequences']['genotype_array'])
        cds_fst = calc_fst_pairwise(self, cds_seq_array)
        aa_fst = calc_fst_pairwise(self, aa_array)
        ss_fst = calc_fst_pairwise(self, ss_array) if ss_array is not None else 0
        ns_fst = calc_fst_pairwise(self, ns_array) if ns_array is not None else 0
        # make dataframes
        gene_fst = triang2df_fst(gene_fst)
        gene_fst['gene_fst'] = gene_fst['fst']
        gene_fst.drop(['fst'], axis=1, inplace=True)
        cds_fst = triang2df_fst(cds_fst)
        cds_fst['cds_fst'] = cds_fst['fst']
        cds_fst.drop(['fst'], axis=1, inplace=True)
        aa_fst = triang2df_fst(aa_fst)
        aa_fst['aa_fst'] = aa_fst['fst']
        aa_fst.drop(['fst'], axis=1, inplace=True)
        ss_fst = triang2df_fst(ss_fst)
        ss_fst['ss_fst'] = ss_fst['fst']
        ss_fst.drop(['fst'], axis=1, inplace=True)
        ns_fst = triang2df_fst(ns_fst)
        ns_fst['ns_fst'] = ns_fst['fst']
        ns_fst.drop(['fst'], axis=1, inplace=True)
        # merge dataframes
        df = pd.merge(gene_fst, cds_fst, on=['loc1', 'loc2'])
        df = pd.merge(df, aa_fst, on=['loc1', 'loc2'])
        df = pd.merge(df, ss_fst, on=['loc1', 'loc2'])
        df = pd.merge(df, ns_fst, on=['loc1', 'loc2'])  
        return df

    def _sort_vcf(self, callset, samples, locs=False):
        """Sort VCF file by samples"""
        sampleIDs = samples['sample_id'].tolist()
        sampleIDs = np.array(sampleIDs)
        sample_indices = np.array([[-1, np.nan] if len(np.where(callset['samples'] == i)[0]) == 0 # remove if no match in VCF
                        else [[-1 if len(np.where(sampleIDs == i)[0]) == 0 # remove if no match in metadata
                        else np.where(sampleIDs == i)[0][0]][0], np.where(callset['samples'] == i)[0][0]]
                        for i in sampleIDs])
        sample_indices = sample_indices[sample_indices[:,0] != -1]
        sample_indices = sample_indices.astype(int)
        sampleIDs = sampleIDs[sample_indices[:,0]]
        callset['calldata/GT'] = allel.GenotypeArray(callset['calldata/GT'][:,sample_indices[:,1],:])
        callset['samples'] = sampleIDs
        # double check that genotypes match
       # assert (genotypes[:,0:1] == allel.GenotypeArray(callset['calldata/GT'][:,sample_indices[0:1,1],:])).all()
        # re-sort metadata
        samples.index = samples['sample_id']
        samples = samples.reindex(sampleIDs)
        if locs:
            assert ('latitude' in samples.columns and 'longitude' in samples.columns) or ('x' in samples.columns and 'y' in samples.columns), "Metadata file must contain 'latitude' and 'longitude' or 'x' and 'y' columns for location data."
            try: 
                sampleLOCs = np.array([samples['longitude'], samples['latitude']]).T
            except:
                sampleLOCs = np.array([samples['x'], samples['y']]).T
        else:
            sampleLOCs = None
        return(callset, sampleIDs, sampleLOCs)


    

##################################################################

def _parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description="Calculate popgen statistics for a gene in a VCF file")
    parser.add_argument('--gene', type=str, help='Gene name to analyze', required=True)
    parser.add_argument('--transcript', type=str, help='Transcript ID from gene to analyze (optional)', default=None)
    parser.add_argument('--vcf', type=str, help='Path to the VCF file', required=True)
    parser.add_argument('--filter', type=str, help='Path to the filter VCF file (optional)', default=None)
    parser.add_argument('--annotation', help='Path to genome annotation DB (created by parse_gff.py)', type=str, required=True)
    parser.add_argument('--fasta', type=str, help='Path to the reference genome FASTA file', required=True)
    parser.add_argument('--proteinfasta', type=str, help='Path to the reference protein FASTA file (for checking amino acid sequences)', default=None)
    parser.add_argument('--metadata', type=str, help='Path to metadata file (optional)', default=None)
    parser.add_argument('--chromosome', type=str, help='Chromosome of the gene', default=None)
    parser.add_argument('--start', type=int, help='Start position of the gene', default=None)
    parser.add_argument('--end', type=int, help='End position of the gene', default=None)
    parser.add_argument('--pi', default=True, action='store_false', help='disable calculation of nucleotide diversity (pi).')
    parser.add_argument('--theta', default=True, action='store_false', help='disable calculation of Watterson\'s theta.')
    parser.add_argument('--tajD', default=True, action='store_false', help='disable calculation of Tajima\'s D.')
    parser.add_argument('--Fst', default=False, action='store_true', help='Calculate pairwise Fst between samples. Default is False.')
    parser.add_argument('--output', type=str, default=None, help='Save statistics to this file if provided. If file exists, append to it, if not, create a new file.')
    parser.add_argument('--print', default=True, action='store_false', help='disable print statistics to the console.')
    return parser.parse_args()

##########################################################
# Functions for dealing with nucleotide and amino acid sequences
##########################################################

def count_sites(cds_seq, aa_seq):
    """ 
    calculate number of silent and non-silent sites in a coding sequence 
    returns array with shape (n_codons, 2) where:
    - first column is the number of silent sites per codon (divided by 3)
    - second column is the number of non-silent sites per codon (divided by 3)
    stop codons are excluded from the count
    """
    codons = np.split(cds_seq, len(aa_seq))
    codon_ss_sites = np.empty((len(codons), 2), dtype=float)

    for i, codon in enumerate(codons):
        silent_sites = 0
        non_silent_sites = 0
        originalAA = codontab[''.join(codon)]
        assert originalAA == aa_seq[i], f"Original AA {originalAA} does not match expected {aa_seq[i]} at position {i}."
        states = ["A", "C", "G", "T"]
        for codonpos in range(3):
            for state in states:
                new_codon = codon.copy()
                new_codon[codonpos] = state
                if ''.join(new_codon) == ''.join(codon):
                    continue
                newAA = codontab[''.join(new_codon)]
                if newAA == originalAA:
                    silent_sites += 1
                elif newAA == '*':
                    # stop codon, we don't count these as silent or non-silent
                    continue
                else:
                    non_silent_sites += 1
        codon_ss_sites[i][0] = silent_sites/3
        codon_ss_sites[i][1] = non_silent_sites/3
    return codons, codon_ss_sites

def mean_ss_sites(cds_seq_array, aa_seq):
    """
    calculate mean number of silent and non-silent sites across all sequences
    """
    ss_sites = np.empty((len(cds_seq_array[0,:]), 2), dtype=float)
    for i in range(len(cds_seq_array[0,:])):
        for j in [0, 1]:
            aa_seq_arr = codonalign.codonseq.CodonSeq("".join(cds_seq_array[:, i, j])).translate()
            c_a, s_a, = count_sites(cds_seq_array[:, i, j], aa_seq_arr)
            ss_sites[i, :] = np.sum(s_a, axis=0)
    mean_silent_sites = np.mean(ss_sites[:, 0])
    mean_non_silent_sites = np.mean(ss_sites[:, 1])
    return mean_silent_sites, mean_non_silent_sites

def get_nucleotide_sequences(callset, coding_seq):
    """get coding sequences from a VCF file and create an array of nucleotide sequences."""
    positions = callset['variants/POS']
    positionmask = np.repeat(False, len(positions))
    for start, end in zip(coding_seq['cds_start'], coding_seq['cds_end']):
        positionmask[(positions >= start) & (positions <= end)] = True
    positions = positions[positionmask]
    alt = callset['variants/ALT'][positionmask]  # alternate alleles for variant positions
    gt = allel.GenotypeArray(callset['calldata/GT'][positionmask]) # genotype calls for variant positions

    if coding_seq['strand'] == '-':
        cds_seq = [str(Seq(x).reverse_complement()) for x in coding_seq['cds_seq']] # reverse complement the coding sequence if on the reverse strand
        cds_seq = np.fromiter("".join(cds_seq), dtype='U1') # numpy array of coding sequence
        cds_positions = np.concatenate([np.flip(np.arange(s, e+1)) for s, e in zip(coding_seq['cds_start'], coding_seq['cds_end'])])
        complement_dict = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C', 'N': 'N'}
    else:
        cds_seq = np.fromiter("".join(coding_seq['cds_seq']), dtype='U1') # numpy array of coding sequence
        cds_positions = np.concatenate([np.arange(s, e+1) for s, e in zip(coding_seq['cds_start'], coding_seq['cds_end'])])
    assert(np.all(cds_seq[0:3] == ['A','T','G'])) # ensure start codon
    cds_seq_array = np.tile(cds_seq, (2, gt.shape[1], 1)).T
    variant_cds_positions, variant_cds_index, variant_position_index = np.intersect1d(cds_positions, positions, return_indices=True) # find intersection of CDS and variant positions
    for vcp, vci, vpi in zip(variant_cds_positions, variant_cds_index, variant_position_index):
        for i in np.unique(gt[vpi]):
            if i > 0:
                if coding_seq['strand'] == '-':
                    altNT = complement_dict[alt[vpi][i-1]] 
                else:
                    altNT = alt[vpi][i-1]
                assert(altNT != cds_seq[vci]) # ensure alternate allele is not the same as the reference
                cds_seq_array[vci][gt[vpi]==i] = altNT    

    return cds_seq, cds_seq_array

def get_aa_sequences(cds_seq_array, cds_seq, ID=None, fasta_check=None):
    """Translate array of coding sequences into protein sequences."""
    wt_AA_seq = np.fromiter(codonalign.codonseq.CodonSeq("".join(cds_seq)).translate(), dtype='U1')  # wild-type coding sequence
    aa_array = np.apply_along_axis(lambda x: np.fromiter(codonalign.codonseq.CodonSeq("".join(x)).translate(), dtype='U1'), 0, cds_seq_array) # array of AA sequences (translated)
    if fasta_check:
        pdct = SeqIO.index(fasta_check, 'fasta')
        assert(np.all(np.fromiter(pdct[ID.replace('R','P')].seq, dtype='U1') == wt_AA_seq[:-1]))
    return wt_AA_seq, aa_array

def identify_ss_ns_sites(cds_seq_array, cds_seq, aa_array, wt_AA_seq):
    """Identify synonymous and non-synonymous mutations in the array of coding sequences."""
    codon_array = np.split(cds_seq, len(cds_seq) // 3)
    synonymous_array = np.zeros(cds_seq_array.shape, dtype='U10')
    nonsynonymous_array = np.zeros(cds_seq_array.shape, dtype='U10')
    for i in range(len(aa_array[0, :, 0])):
        for j in [0, 1]:
            codons = np.split(cds_seq_array[:, i, j], len(cds_seq)//3)
            mutcodons = np.where([codons[x] != codon_array[x] for x in range(len(codon_array))])
            mutloci = mutcodons[0]*3 + mutcodons[1]  # calculate the mutation loci in the codon array
            nscodons = np.where(aa_array[:, i, j] != wt_AA_seq)[0]
            #print(np.isin(mutcodons[0], nscodons))
            nsloci = mutloci[np.isin(mutcodons[0], nscodons)]
            sscodons = np.array([x for x in mutcodons[0] if x not in nscodons])
            ssloci = mutloci[np.isin(mutcodons[0], sscodons)]
            if len(ssloci) > 0:
                synonymous_array[ssloci, i, j] = cds_seq_array[ssloci, i, j]
            if len(nsloci) > 0:
                nonsynonymous_array[nsloci, i, j] = cds_seq_array[nsloci, i, j]
    return synonymous_array, nonsynonymous_array

def convert_to_binaryarray(sequence_array, wt_sequence):
    """ convert nt or amino acid sequences to binary array format for genotype calls """
    for i in range(sequence_array.shape[0]):
        wt_val = wt_sequence[i]
        all_val = np.unique(sequence_array[i, :, :])
        all_val = np.roll(all_val, -1*np.where(all_val == wt_val)[0])
        for a in range(len(all_val)):
            val_id = all_val[a]
            msk = sequence_array[i, :, :] == val_id
            sequence_array[i, msk] = a  # replace amino acid with its index
    sequence_array = sequence_array.astype(int)  # convert to integer type
    sequence_array = allel.GenotypeArray(sequence_array)
    nonvariant_mask = sequence_array.count_hom_ref(axis=1) < sequence_array.shape[1]
    sequence_array = sequence_array[nonvariant_mask]
    if len(sequence_array) == 0:
        return None
    else:
        return sequence_array

def triang2df_fst(mtx1):
    mtx1 = mtx1.where(np.triu(np.ones(mtx1.shape)).astype(bool))
    mtx1 = mtx1.stack().reset_index()
    mtx1.columns = ['loc1', 'loc2', 'fst']
    mtx1 = mtx1.dropna()
    return mtx1

##################################################################
# Functions for calculating statistics
##################################################################

def calc_pi(sequence_array, nsites):
    """Calculate nucleotide diversity (pi) for a given sequence array."""
    # manually calculate pi, stolen from scikit-allel
    if sequence_array is None or len(sequence_array) == 0:
        return 0
    else:
        ac = sequence_array.count_alleles()
        an = np.sum(ac, axis=1)
        n_pairs = an * (an - 1) / 2
        n_same = np.sum(ac * (ac - 1) / 2, axis=1) 
        n_diff = n_pairs - n_same
        mpd = n_diff / n_pairs
        mpd_sum = np.sum(mpd)
        pi = mpd_sum / nsites if nsites > 0 else 0
        return pi

def calc_theta(sequence_array, nsites):
    """Calculate Watterson's theta (theta hat per base) for a given sequence array."""
    # manually calculate Watterson's estimator (theta hat per base)
    # stolen from scikit-allel
    if sequence_array is None or len(sequence_array) == 0:
        return 0
    else:
        ac = sequence_array.count_alleles()
        # count segregating variants
        S = ac.count_segregating()
        # assume number of chromosomes sampled is constant for all variants
        n = ac.sum(axis=1).max()
        # (n-1)th harmonic number
        a1 = np.sum(1 / np.arange(1, n))
        # calculate absolute value
        theta_hat_w_abs = S / a1
        # calculate value per base
        theta_hat_w = theta_hat_w_abs / nsites if nsites > 0 else 0
        return theta_hat_w

def calc_taj(sequence_array, nsites, min_sites=3):
    """Manually calculate Tajima's D."""
    # stolen from scikit-allel
    if sequence_array is None or len(sequence_array) == 0:
        return 0
    ac = sequence_array.count_alleles()
    S = ac.count_segregating()
    if S < min_sites:
        return np.nan
    # assume number of chromosomes sampled is constant for all variants
    n = ac.sum(axis=1).max()
    # (n-1)th harmonic number
    a1 = np.sum(1 / np.arange(1, n))
    # calculate Watterson's theta (absolute value)
    theta_hat_w_abs = S / a1
    # calculate mean pairwise difference
    an = np.sum(ac, axis=1)
    n_pairs = an * (an - 1) / 2
    n_same = np.sum(ac * (ac - 1) / 2, axis=1) 
    n_diff = n_pairs - n_same
    mpd = n_diff / n_pairs
    # calculate theta_hat pi (sum differences over variants)
    theta_hat_pi_abs = np.sum(mpd)
    # N.B., both theta estimates are usually divided by the number of
    # (accessible) bases but here we want the absolute difference
    d = theta_hat_pi_abs - theta_hat_w_abs
    # calculate the denominator (standard deviation)
    a2 = np.sum(1 / (np.arange(1, n)**2))
    b1 = (n + 1) / (3 * (n - 1))
    b2 = 2 * (n**2 + n + 3) / (9 * n * (n - 1))
    c1 = b1 - (1 / a1)
    c2 = b2 - ((n + 2) / (a1 * n)) + (a2 / (a1**2))
    e1 = c1 / a1
    e2 = c2 / (a1**2 + a2)
    d_stdev = np.sqrt((e1 * S) + (e2 * S * (S - 1)))
    # finally calculate Tajima's D
    D = d / d_stdev if d_stdev > 0 else np.nan

    return D

def calc_fst_btwn(gene, seqs, loc1, loc2):
    """Calculate Hudson's Fst between two locations."""
    locs = gene.locs
    assert sum(seqs.count_hom_ref(axis=1) == seqs.shape[1]) == 0 # no all-ref variants
    ind1 = np.where((locs == loc1).all(1))[0]
    ind2 = np.where((locs == loc2).all(1))[0]
    ac1 = seqs[:, ind1].count_alleles()
    ac2 = seqs[:, ind2].count_alleles()
    n, d = allel.hudson_fst(ac1, ac2, fill=np.nan)
    with np.errstate(invalid='ignore'):
        fst = np.nansum(n) / np.nansum(d)
    return fst

def calc_fst_pairwise(gene, seqs):
    """Calculate pairwise Fst between all locations."""
    locs = np.unique(gene.locs, axis=0)
    fstmat = pd.DataFrame(index=[tuple(i) for i in locs], columns=[tuple(i) for i in locs])
    for i, j in itertools.combinations(locs, 2):
        itup = tuple(i)
        jtup = tuple(j)
        fst = calc_fst_btwn(gene, seqs, i, j)
        fstmat[itup][jtup] = fst
        fstmat[jtup][itup] = fst
    return fstmat 

###################################################################

def main():
    """Popgen statistics for a gene..."""
    args = _parse_args()
    if not args.vcf or not args.gene or not args.annotation or not args.fasta:
        raise ValueError("Please provide all required arguments: --vcf, --gene, --annotation, --fasta")
    GENE = Gene(name=args.gene, chromosome=args.chromosome, start=args.start, end=args.end,
                statistics={'pi':args.pi,
                            'theta':args.theta,
                            'tajD':args.tajD,
                            'Fst':args.Fst})
    GENE.fetch_gene_coordinates(annotation=args.annotation, fasta=args.fasta)
    GENE.fetch_gene_transcripts(annotation=args.annotation)
    if args.metadata:
        samples = pd.read_csv(args.metadata, sep='\t')
    else:
        samples = None
    GENE.fetch_variation(
        vcf_file=args.vcf,
        annotation=args.annotation,
        fasta=args.fasta,
        locs=True if args.Fst else False,
        protein_fasta=args.proteinfasta,
        samples=samples,
        filter=args.filter
    )
    if args.transcript:
        if args.transcript not in GENE.transcripts:
            raise ValueError(f"Transcript {args.transcript} not found in gene {GENE.name}. Available transcripts: {list(GENE.transcripts.keys())}")
        GENE.calculate_statistics(transcriptID=args.transcript)  # calculate statistics for the specified transcript
        if args.output:
            if os.path.exists(args.output):
                GENE.save_to_df(transcriptID=args.transcript, output_file=args.output, append=True)
            else:
                GENE.save_to_df(transcriptID=args.transcript, output_file=args.output, append=False)
        if args.print:
            print(f"Statistics for transcript {args.transcript} of gene {GENE.name} written to {args.output}")
    else:
        for K in GENE.transcripts.keys():
            GENE.calculate_statistics(transcriptID=K)  # calculate statistics for each transcript
            if args.output:
                if os.path.exists(args.output):
                    GENE.save_to_df(transcriptID=K, output_file=args.output, append=True)
                else:
                    GENE.save_to_df(transcriptID=K, output_file=args.output, append=False)
            if args.print:
                print(f"Statistics for transcript {K} of gene {GENE.name} written to {args.output}")


if __name__ == "__main__":
    start_time = time.time()
    main()
    end_time = time.time()
    print(f"Execution time: {end_time - start_time:.2f} seconds")